docs:
  - "*.md"
  - "".env.example"

actions:
  - ".github/*"

test:
  - "*/tests/*"

features:
  - "controllers/*"
  - "models/*"
  - "routes/*"
  - "middlewares/*"
  - "services/*"
  - "helpers/*"
  - "app.ts"
  - "router.ts"

config:
  - "tsconfig.json"
  - "eslintrc.json"
  - "Dockerfile"
  - ".dockerignore"
  - ".gitignore"        
  - ".prettierrc"
  - "jest.config.js"

packages:
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"
